In [3]:
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

# Import necessary packages
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

from mlxtend.frequent_patterns import apriori, association_rules, fpgrowth

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [4]:
# Load Data Set
df = pd.read_excel("Online retail.xlsx")
df.head()

  shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
0                             burgers,meatballs,eggs
1                                            chutney
2                                     turkey,avocado
3  mineral water,milk,energy bar,whole wheat rice...
4                                     low fat yogurt

In [5]:
# Dataset Shape
df.shape

(7500, 1)

In [6]:
# Data Type
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7500 entries, 0 to 7499
Data columns (total 1 columns):
 #   Column                                                                                                                                                                                                                           Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                           --------------  -----
 0   shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil  7500 non-null   object
dtypes: object(1)
memory usage: 58.7+ KB

In [7]:
df.columns

Index(['shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil'], dtype='object')

In [8]:
# check missing Values
df.isnull().sum()

shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil    0
dtype: int64

In [9]:
df.columns= ["Items"] # renaming all column headers of the DataFrame to a single column

In [10]:
df

                                                  Items
0                                burgers,meatballs,eggs
1                                               chutney
2                                        turkey,avocado
3     mineral water,milk,energy bar,whole wheat rice...
4                                        low fat yogurt
...                                                 ...
7495                      butter,light mayo,fresh bread
7496  burgers,frozen vegetables,eggs,french fries,ma...
7497                                            chicken
7498                                 escalope,green tea
7499    eggs,frozen smoothie,yogurt cake,low fat yogurt

[7500 rows x 1 columns]

In [11]:
df.describe()

          Items
count      7500
unique     5175
top     cookies
freq        223

In [12]:
transactions = df["Items"].apply(lambda x: x.split(",")).tolist() #converts each row of the Items column into a list of items by splitting on commas
transactions[:5]

[['burgers', 'meatballs', 'eggs'],
 ['chutney'],
 ['turkey', 'avocado'],
 ['mineral water', 'milk', 'energy bar', 'whole wheat rice', 'green tea'],
 ['low fat yogurt']]

In [13]:
from mlxtend.preprocessing import TransactionEncoder
#converting item lists into a binary matrix
te = TransactionEncoder()
te_ary = te.fit(transactions).transform(transactions)

df_encoded = pd.DataFrame(te_ary, columns=te.columns_)
df_encoded.head()

,asparagus,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,black tea,blueberries,...,turkey,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,True,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [14]:
from mlxtend.frequent_patterns import apriori, association_rules

frequent_itemsets = apriori(df_encoded, min_support=0.01, use_colnames=True) #keeping only those appearing in ≥1% of all transaction.
frequent_itemsets.sort_values(by="support", ascending=False).head(10) #displays the top 10 most frequent item combinations.

     support             itemsets
46  0.238267      (mineral water)
19  0.179733               (eggs)
63  0.174133          (spaghetti)
24  0.170933       (french fries)
13  0.163867          (chocolate)
32  0.132000          (green tea)
45  0.129600               (milk)
33  0.098267        (ground beef)
30  0.095333  (frozen vegetables)
53  0.095067           (pancakes)

In [15]:
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.2) # filters rules with confidence ≥ 20%
rules.sort_values(by="lift", ascending=False).head(10)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
75,(herb & pepper),(ground beef),0.049467,0.098267,0.016000,0.323450,3.291555,1.0,0.011139,1.332841,0.732423,0.121457,0.249723,0.243136
154,"(mineral water, spaghetti)",(ground beef),0.059733,0.098267,0.017067,0.285714,2.907540,1.0,0.011197,1.262427,0.697745,0.121097,0.207875,0.229696
69,(tomatoes),(frozen vegetables),0.068400,0.095333,0.016133,0.235867,2.474134,1.0,0.009613,1.183913,0.639564,0.109304,0.155344,0.202549
67,(shrimp),(frozen vegetables),0.071333,0.095333,0.016667,0.233645,2.450820,1.0,0.009866,1.180480,0.637444,0.111111,0.152887,0.204235
144,"(milk, mineral water)",(frozen vegetables),0.048000,0.095333,0.011067,0.230556,2.418415,1.0,0.006491,1.175740,0.616078,0.083669,0.149472,0.173320
152,"(mineral water, ground beef)",(spaghetti),0.040933,0.174133,0.017067,0.416938,2.394361,1.0,0.009939,1.416431,0.607207,0.086195,0.294000,0.257474
145,"(frozen vegetables, mineral water)",(milk),0.035733,0.129600,0.011067,0.309701,2.389672,1.0,0.006436,1.260904,0.603083,0.071737,0.206918,0.197546
151,"(milk, mineral water)",(ground beef),0.048000,0.098267,0.011067,0.230556,2.346223,1.0,0.006350,1.171928,0.602713,0.081854,0.146705,0.171587
90,(soup),(milk),0.050533,0.129600,0.015200,0.300792,2.320923,1.0,0.008651,1.244836,0.599428,0.092158,0.196681,0.209038
79,(ground beef),(spaghetti),0.098267,0.174133,0.039200,0.398915,2.290857,1.0,0.022088,1.373959,0.624888,0.168096,0.272176,0.312015

In [21]:
final_rules = rules[(rules['confidence'] > 0.2) & (rules['lift'] > 1.2)] #confidence > 20% and lift > 1.2
final_rules.sort_values(by="lift", ascending=False).head(3)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
75,(herb & pepper),(ground beef),0.049467,0.098267,0.016000,0.323450,3.291555,1.0,0.011139,1.332841,0.732423,0.121457,0.249723,0.243136
154,"(mineral water, spaghetti)",(ground beef),0.059733,0.098267,0.017067,0.285714,2.907540,1.0,0.011197,1.262427,0.697745,0.121097,0.207875,0.229696
69,(tomatoes),(frozen vegetables),0.068400,0.095333,0.016133,0.235867,2.474134,1.0,0.009613,1.183913,0.639564,0.109304,0.155344,0.202549

Interview Questions

`Problem 1` What is lift and why is it important in Association rules?


**Lift** measures the strength of association between two items beyond random chance, and it is important because it identifies truly meaningful and actionable relationships in association rule mining.

`Problem 2` What is support and Confidence. How do you calculate them?

"Support" measures how frequently an itemset appears in the dataset.

Support(A → B) = count(A ∩ B) / total transactions

"Confidence" measures the reliability of a rule.

Confidence(A → B) = count(A ∩ B) / count(A)

`Problem 3` What are some limitations or challenges of Association rules mining?

Limitations of Association Rule Mining:

*   Computationally expensive for large datasets
*   Generates too many trivial or redundant rules
*   Rare but important patterns may be missed
*   Does not imply causation, only correlation
*   Requires careful threshold tuning for support and confidence